#' Convert data.frames to text
#'
#' @description
#' Convenience function for converting DFs originally generated by create_ocr to character vectors.
#' Can handle lists (for multiple pages) or character vectors.
#'
#' @param texts List of or single data.frame with column "word", which is extracted
#' @returns List of character vectors or single character vector, depending on input.
convert_dfs_to_text <- function(texts) {
  assert(
    test_list(texts),
    test_data_frame(texts),
    combine = "or"
  )

  res <- if (is.list(texts)) {
    lapply(texts, function(text_df) {
      base::paste(text_df[["word"]], collapse = " ")
    })
  } else {
    base::paste(texts[["word"]], collapse = " ")
  }
  res
}

# conversion function:
# px to pi, mm, cm


# check_and_load <- function(package_name) {
#   if (!require(package_name, character.only = TRUE)) {
#     install.packages(package_name)
#     library(package_name, character.only = TRUE)
#   }
# }
